import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./themeRegistry";

import { Box } from "@mui/material";
import Sidebar from "./components/Sidebar";
import DrawerHeader from "./components/DrawerHeader";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <Box sx={{ display: "flex" }}>
            <Sidebar />
            <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
              <DrawerHeader />
              {children}
            <Footer/>
            </Box>
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
